# Numpy

## 1. Numpy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Generate Array
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [28]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Generate matrix with uniform distribution
np.random.rand(5)

array([0.01247157, 0.18326579, 0.72222995, 0.50265971, 0.74159805])

In [44]:
# Generate matrix with standard normal distribution (around 0)
np.random.randn(2,4)

array([[ 1.72072577,  1.52270617, -0.59455412,  0.75062311],
       [-2.54381678,  1.3921045 , -1.1253979 , -1.05007152]])

In [47]:
# Generate number(s) from x to y
np.random.randint(1,100, 10)

array([25, 34, 25, 28, 90, 57, 89, 17, 74, 23])

In [48]:
ranarr = np.random.randint(0,50,10)

In [49]:
ranarr

array([18, 25, 43, 42, 17, 24, 15, 13, 38, 37])

In [139]:
arr = np.arange(30)

In [67]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [70]:
# Find max
ranarr.max()

43

In [72]:
# Find Min
ranarr.min()

13

In [73]:
ranarr.argmin()

7

In [74]:
ranarr.argmax()

2

In [75]:
arr.shape

(30,)

In [76]:
arr.dtype

dtype('int64')

## 2. Numpy Indexing & Selection

In [77]:
arr = np.arange(0,11)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[3]

3

In [85]:
arr[:5]

array([0, 1, 2, 3, 4])

In [87]:
arr[:11:2]

array([ 0,  2,  4,  6,  8, 10])

In [88]:
arr[:5] = 100

In [89]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [90]:
arr = np.arange(0,11)

In [91]:
slice_of_arr = arr[0:6]

In [92]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [93]:
slice_of_arr[:] = 99

In [96]:
# Numpy by default doesn't copy array, it just provides a view
# into the original
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [98]:
# Copy array
copy = arr.copy()

## 3. Index 2D Arrays

In [100]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [101]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [103]:
# Index Row
arr_2d[0]

array([ 5, 10, 15])

In [105]:
# Index element in row
arr_2d[2][1]

40

In [106]:
arr_2d[2,1]

40

In [109]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [110]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [111]:
arr = np.arange(1,11)

In [112]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
bool_arr = arr > 5

In [115]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [116]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [117]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [118]:
arr[arr < 3]

array([1, 2])

In [119]:
arr_2d = np.arange(50).reshape(5,10)

In [120]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [121]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [122]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## 4. Numpy Operations 

In [123]:
arr = np.arange(0,11)

In [124]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [127]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [128]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [129]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [132]:
arr / arr

/var/folders/vn/x8v3rrm528n3gfr1x5x25lg80000gn/T/ipykernel_22951/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [133]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [134]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [135]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [137]:
np.max(arr)

10

In [138]:
np.log(arr)

/var/folders/vn/x8v3rrm528n3gfr1x5x25lg80000gn/T/ipykernel_22951/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
np.